# Generated by Django 5.0.14 on 2026-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incubator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('incubator_type', models.CharField(choices=[('incubator', 'Incubator'), ('accelerator', 'Accelerator'), ('both', 'Both')], max_length=20)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='incubators/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('focus_industries', models.TextField(help_text='Comma separated industries')),
                ('programs', models.TextField(blank=True, help_text='Description of programs offered', null=True)),
                ('funding_range', models.CharField(blank=True, max_length=200, null=True)),
                ('application_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
