# Generated by Django 5.0.14 on 2026-06-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('growth_rate', models.DecimalField(decimal_places=2, help_text='Growth rate in %', max_digits=5)),
                ('market_size', models.DecimalField(decimal_places=2, help_text='Market size in USD', max_digits=15)),
                ('icon', models.CharField(default='bi-graph-up', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-growth_rate'],
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('market_share', models.DecimalField(decimal_places=2, help_text='Market share in %', max_digits=5)),
                ('strength', models.TextField()),
                ('weakness', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='ideas.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_market_size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('target_audience', models.TextField()),
                ('growth_opportunities', models.TextField()),
                ('key_trends', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_analyses', to='ideas.startupidea')),
            ],
        ),
    ]
