# Generated by Django 5.0.14 on 2026-06-28 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_challenge_userchallenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-earned_at']},
        ),
        migrations.AlterModelOptions(
            name='userchallenge',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AddField(
            model_name='badge',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('idea', 'Idea Submission'), ('evaluation', 'Evaluation'), ('mentor', 'Mentorship'), ('community', 'Community'), ('milestone', 'Milestone'), ('special', 'Special'), ('verified', 'Verified'), ('award', 'Award')], default='special', max_length=20),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='bi-award', help_text='Bootstrap icon class', max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='icon',
            field=models.CharField(default='bi-star', max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gamification.badge'),
        ),
        migrations.CreateModel(
            name='VerifiedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('startup', 'Verified Startup'), ('mentor', 'Verified Mentor'), ('investor', 'Verified Investor')], max_length=20)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verified_badge', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('innovator', 'Monthly Innovator'), ('community_choice', 'Community Choice'), ('rising_star', 'Rising Star'), ('top_mentor', 'Top Mentor')], max_length=30)),
                ('month', models.DateField(help_text='First day of the month')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('user', 'award_type', 'month')},
            },
        ),
    ]
