# Generated by Django 5.0.14 on 2026-06-28 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0002_startupidea_encrypted_pitch_deck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_type', models.CharField(choices=[('business_model', 'Business Model Canvas'), ('lean', 'Lean Canvas'), ('swot', 'SWOT Canvas'), ('value_proposition', 'Value Proposition Canvas'), ('customer_persona', 'Customer Persona'), ('user_journey', 'User Journey Map'), ('risk_matrix', 'Risk Matrix'), ('okr', 'OKR Planner')], max_length=30)),
                ('data', models.JSONField(default=dict, help_text='Canvas data as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_projects', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_projects', to='ideas.startupidea')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
