# Generated by Django 5.0.14 on 2026-06-28 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0002_startupidea_encrypted_pitch_deck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('block_number', models.PositiveIntegerField(editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_timestamp', to='ideas.startupidea')),
            ],
            options={
                'ordering': ['-block_number'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('idea_name', models.CharField(max_length=200)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('idea_timestamp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='blockchain.ideatimestamp')),
            ],
        ),
    ]
