# Generated by Django 5.0.14 on 2026-06-28 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0002_startupidea_encrypted_pitch_deck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('seed', 'Seed Round'), ('angel', 'Angel Investment'), ('pre_seed', 'Pre-Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('grant', 'Grant'), ('bootstrapped', 'Bootstrapped'), ('revenue', 'Revenue Funded')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('investor_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_timeline', to='ideas.startupidea')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='KpiDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_active_users', models.IntegerField(default=0)),
                ('revenue_mrr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('burn_rate', models.DecimalField(decimal_places=2, default=0, help_text='Monthly burn rate', max_digits=15)),
                ('runway_months', models.IntegerField(default=0)),
                ('customer_acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_margin', models.DecimalField(decimal_places=2, default=0, help_text='Percentage', max_digits=5)),
                ('churn_rate', models.DecimalField(decimal_places=2, default=0, help_text='Monthly churn %', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_dashboard', to='ideas.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='StartupHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0, help_text='Overall health score 0-100')),
                ('team_score', models.IntegerField(default=0)),
                ('market_score', models.IntegerField(default=0)),
                ('product_score', models.IntegerField(default=0)),
                ('financial_score', models.IntegerField(default=0)),
                ('traction_score', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_score', to='ideas.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('projected_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('projected_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_forecasts', to='ideas.startupidea')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('idea', 'month')},
            },
        ),
    ]
