# Generated by Django 5.0.14 on 2026-06-28 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_chatroom_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('audio_url', models.URLField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='podcasts/')),
                ('host', models.CharField(blank=True, max_length=200)),
                ('guest', models.CharField(blank=True, max_length=200)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('presenter', models.CharField(max_length=200)),
                ('presenter_bio', models.TextField(blank=True)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('registration_link', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('max_attendees', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userfollow',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='startupshowcase',
            name='featured_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupshowcase',
            name='funding_raised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='achievement',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=300)),
                ('is_resolved', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='community.forumquestion')),
            ],
            options={
                'ordering': ['-is_accepted', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_registrations', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='community.webinar')),
            ],
            options={
                'unique_together': {('webinar', 'user')},
            },
        ),
    ]
